apiVersion: v1
kind: Service
metadata:
  name: byulmaru-co
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: id
  selector:
    app: byulmaru-co
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: byulmaru-co
  annotations:
    secrets.infisical.com/auto-reload: 'true'
  labels:
    app: byulmaru-co
spec:
  selector:
    matchLabels:
      app: byulmaru-co
  template:
    metadata:
      labels:
        app: byulmaru-co
    spec:
      enableServiceLinks: false
      containers:
        - name: byulmaru-co
          image: ghcr.io/byulmaru/byulmaru.co
          envFrom:
            - secretRef:
                name: env
          resources:
            requests:
              cpu: '100m'
              memory: '256Mi'
            limits:
              cpu: '500m'
              memory: '1Gi'
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: oci.oraclecloud.com/oke-is-preemptible
                    operator: Exists
                    values: []
      tolerations:
        - key: 'oci.oraclecloud.com/oke-is-preemptible'
          operator: 'Equal'
          value: 'present'
          effect: 'NoSchedule'
      priorityClassName: preemptible
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: byulmaru-co
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: byulmaru-co
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: byulmaru-co
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: byulmaru-co
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
