apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate
spec:
  secretName: certificate
  issuerRef:
    name: cert-issuer
    kind: ClusterIssuer
  dnsNames:
    - id.byulmaru.co
