apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: env
spec:
  resyncInterval: 60
  authentication:
    kubernetesAuth:
      identityId: 953a7c79-6486-44d6-a6be-04dd7eda1853
      autoCreateServiceAccountToken: true
      serviceAccountRef:
        name: secret
        namespace: infisical

      secretsScope:
        projectId: 1cb9b685-b73f-4d00-95f9-eb0abd2c8770
        envSlug: prod
        secretsPath: /
  managedKubeSecretReferences:
    - secretName: env
      secretNamespace: byulmaru-co
      creationPolicy: Owner
      secretType: Opaque
